#!/usr/bin/env python3
"""
relay_agent.py — Docker relay agent for NVIDIA ICLAD25 harness

This agent runs inside the Docker container launched by the NVIDIA harness.
It does not generate any RTL. Instead, it copies pre-built RTL files
(generated by agent.py + Codex CLI on the host) from /prebuilt/ into /code/rtl/
so the harness can grade them.

Mount layout (set in docker-compose.yml written by the harness):
  /code/     — harness working directory (read prompt.json, write RTL here)
  /prebuilt/ — host volume mount pointing to the pre-built RTL directory
               (e.g. work/<problem_id>/rtl/)
"""

import shutil
import sys
from pathlib import Path

CODE_DIR   = Path("/code")
PREBUILT   = Path("/prebuilt")
RTL_DIR    = CODE_DIR / "rtl"


def main():
    # Ensure the target rtl/ directory exists
    RTL_DIR.mkdir(parents=True, exist_ok=True)

    if not PREBUILT.exists():
        print("ERROR: /prebuilt mount does not exist. Check docker-compose volume mount.")
        sys.exit(1)

    rtl_files = list(PREBUILT.rglob("*.sv")) + list(PREBUILT.rglob("*.v"))

    if not rtl_files:
        print("ERROR: /prebuilt is empty — no .sv or .v files found.")
        print("       Run agent.py first to generate RTL, then run the harness.")
        sys.exit(1)

    print(f"Relaying {len(rtl_files)} RTL file(s) from /prebuilt to /code/rtl/")
    for src in rtl_files:
        dest = RTL_DIR / src.relative_to(PREBUILT)
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        print(f"  {src.relative_to(PREBUILT)}")

    print("RTL relay complete.")


if __name__ == "__main__":
    main()
